### PR TITLE
New volume icon

### PR DESCRIPTION
**Pull request by rejsmont**
Hi,

I updated the Volume icon to play nicely with the original OS X Volume icons. I also created the external drive volume icon, but AFAIK there is no code that distinguishes between internal vs external ZFS datasets now.

### CODE REVIEW

**Comment by lundman** [comment]
I have checked the icons, but they look the same as before, what is the change here?

**Comment by rejsmont** [comment]
Hi Jorgen,

Screenshot

Top-left - old icon. Bottom-left - new icon. Top-right - OS X drive icon.

**Comment by hoondi** [comment]
I have the original “snow flake” icon set if that is still of interested…

I created back in the macZFS days it so there’s no issue about using it...

**Comment by Fnuxus** [comment]
> I updated the Volume icon to play nicely with the original OS X Volume icons. I also created the external drive volume icon, but AFAIK there is no code that distinguishes between internal vs external ZFS datasets now.

Thanks for your work on the icon! It looks perfect, but it is a bit smaller than the macOS volume icon. Could you make it bigger without too much effort?

**Comment by lundman** [comment]
a432d7d

**Pull request closed without merging**
