### PR TITLE
Metadata Allocation Classes

### PR DESCRIPTION
**Pull request by lundman**
This is the OSX version of: https://github.com/zfsonlinux/zfs/pull/5182

It was easier to include the "status_cbdata_t" changes to prints as well, and we could consider ZOL 8720e9e7482fa2d `Add -c to zpool iostat & status to run command`.

### CODE REVIEW

**Comment by JMoVS** [comment]
does this need testing? And could you maybe tag PRs that need testing with a label à la "needs testing"? Then I can try to have a look

**Comment by lundman** [comment]
```
FAIL	 223
PASS	 645

Running Time:	03:23:56
Percent passed:	74.3%
```

So this passes, looks good for merge.

**Comment by lundman** [comment]
The actual branch:

```
FAIL	 231
PASS	 637

Running Time:	03:06:49
Percent passed:	73.4%
```

**Comment by lundman** [comment]
The alloc_class test scripts needed change `truncate` to `$TRUNCATE`.

Panic in alloc_class_006
```
panic(cpu 1 caller 0xffffff7f842c55eb): "trying to interlock destroyed mutex (0xffffff90a7aebd90)"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4903.240.8/osfmk/i386/locks_i386.c:2817
Backtrace (CPU 1), Frame : Return Address
0xffffff90af37b910 : 0xffffff8001c8601d mach_kernel : _handle_debugger_trap + 0x47d
0xffffff90af37b960 : 0xffffff8001e22cc7 mach_kernel : _kdp_i386_trap + 0x197
0xffffff90af37b9a0 : 0xffffff8001e125f2 mach_kernel : _kernel_trap + 0x3c2
0xffffff90af37ba10 : 0xffffff8001c21ca0 mach_kernel : trap_from_kernel + 0x26
0xffffff90af37ba30 : 0xffffff8001c856d9 mach_kernel : _panic_trap_to_debugger + 0x1b9
0xffffff90af37bb60 : 0xffffff8001c85503 mach_kernel : _panic + 0x63
0xffffff90af37bbd0 : 0xffffff7f842c55eb net.lundman.spl : _spl_mutex_enter + 0x4b
0xffffff90af37bbf0 : 0xffffff7f855466a8 net.lundman.zfs : _vdev_dtl_sync + 0x228
0xffffff90af37bc50 : 0xffffff7f855471eb net.lundman.zfs : _vdev_sync + 0xeb
0xffffff90af37bca0 : 0xffffff7f85532dfb net.lundman.zfs : _spa_sync + 0xb2b
0xffffff90af37bee0 : 0xffffff7f855409f7 net.lundman.zfs : _txg_sync_thread + 0x337
```

**Comment by lundman** [comment]
With the exception of 006, and I had to comment out `zdb -bbcc` for some reason, the tests PASS:

```
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/setup (run as root) [00:00] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_001_pos (run as root) [00:03] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_002_neg (run as root) [00:06] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_003_pos (run as root) [00:01] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_004_pos (run as root) [00:01] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_005_pos (run as root) [00:01] [PASS]

Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_007_pos (run as root) [00:10] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_008_pos (run as root) [00:01] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_009_pos (run as root) [00:10] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_010_pos (run as root) [00:01] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_011_neg (run as root) [00:00] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos (run as root) [00:19] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/alloc_class_013_pos (run as root) [00:15] [PASS]
Test: /Users/lundman/src/zfs/osx.zfs/x/zfs/tests/zfs-tests/tests/functional/alloc_class/cleanup (run as root) [00:00] [PASS]
```

**Comment by lundman** [comment]
I would seem Solaris and ZOL has touched on this issue:  https://github.com/zfsonlinux/zfs/pull/7856

But it is not fixed with ZOLs https://github.com/zfsonlinux/zfs/commit/733b5722b4fc6e7927ea8a33bef49f7059d91903

Repeatedly running
```
# zpool create -f pool mirror disk1 disk0 ; zpool split pool split_pool; zpool destroy pool
```
is enough to trigger here, about ~20 times.

**Comment by lundman** [comment]
After applying ZOL cec8583ee643d37540dd01cd1546d584e5690116 from https://github.com/zfsonlinux/zfs/pull/7856

The panics go away:
```
for i in {1..100}; do zpool create -f pool mirror disk1 disk0 ; zpool split pool split_pool; zpool destroy pool ; sleep 1; done
```

We will take this commit, with thanks :)

**Pull request merged**
