### PR TITLE
Issue183 with snapdev

### PR DESCRIPTION
**Pull request by evansus**
@lundman Could you review these additional changes?
* snapdev was not being checked (default hidden) which can create lots of additional zvol devices
* changing snapdev on live zvols works in the same was as on ZoL:
  * if the zvol is in use, it changes the property but leaves the zvol minor unchanged.
  * after unmounting volumes from an open zvol, you can re-issue `zfs set snapdev=hidden` and it will go away
* uses the dmu_objset_find -> zvol_create_minors_cb style from ZoL 
* snapshot zvol_create_minors checked all the datasets and snapshots in the pool, even though dsl_dataset_snapshot attempted to call zvol_create_minors on each new snapshot (but failed).

### CODE REVIEW

**Comment by ilovezfs** [comment]
@evansus fyi: https://gist.github.com/ilovezfs/fd0b9c51476ce99f045d

**Comment by evansus** [comment]
and https://gist.github.com/ilovezfs/fd0b9c51476ce99f045d#comment-1381288

**Comment by evansus** [comment]
One remaining issue is that zpool_disable_volumes doesn't check for zvol snapshots

**Comment by ilovezfs** [comment]
How can volmode be set per snapshot? It's a persistent property? Are there any other RW snapshot properties? Isn't this why "zfs hold" is as weird as it is?

**Comment by ilovezfs** [comment]
The com.apple.* idea was that it's really Apple - in particular the OS X specific mount options browse/nobrowse (MNT_DONTBROWSE) owners/noowners (MNT_IGNORE_OWNERSHIP), but I suppose we could extend its use or use some reverse dns of our own.

I wonder if we'd be better off finding a way to be directly compatible with the FreeBSD property and use the same name.

**Comment by evansus** [comment]
You're right, I was mistaken in thinking it can be set on the snapshots - but it is inherited and used for snapshots. It can be set on the zvols themselves, and on datasets to inherit down to zvols.

Also I should add that, at least when using the dmu_find_objset -> callback method of creating zvols, the zvol would be created last after creating readonly devices for the snapshots.
So on pool import, you'd see "/Volumes/Test" readonly from the first snapshot, "Test 1" ... "Test n" also snapshots, and "Test N" would be the read-write zvol.

**Comment by ilovezfs** [comment]
So if I'm understanding it correctly, volmode (other than the peculiarity of "dev" mode) is the same as snapdev except that it also applies to the zvol itself?

**Comment by evansus** [comment]
Yes, although I wouldn't say that it's a peculiarity - "dev" mode uses the standard ZFS behavior, "geom" uses the OS specific interface for disk devices, and "none" allows them to be disabled (which would seem to be useful on all platforms, for replicating data to backup pools).

**Comment by ilovezfs** [comment]
So on FreeBSD if I want the zvol itself to be "geom" and all the snapshots of the zvol to be "none," that is not possible in their model?

**Comment by evansus** [comment]
Exactly, but they have not brought in snapdev, not sure why.
One other difference is it is only checked on zvol creation and pool import. zfs rename doesn't change it either, only create, clone, and recv. Avoids issues with an in-use volume, but not the most convenient.

zfs clone can quickly toggle it, essentially (clone, promote, destroy old), either using `zfs clone -o volmode=<newmode>` or cloning into a parent dataset with `volmode=<newmode>` set.

**Comment by ilovezfs** [comment]
```
Exactly, but they have not brought in snapdev, not sure why.
```
Well, FreeBSD doesn't have aggressive auto-mounting like OS X, does it? So even for a volmode=geom the snapshots don't all automatically mount, do they?

**Comment by evansus** [comment]
Yes but geom will taste for partitions, and create links in /dev/gpt /dev/gptid as well.
With just a handful of snapshots, you have lots of duplicate devices visible in `gpart show` etc.
Also multiple devices with matching GPT labels and uuids can result in the 'wrong' device being present in the /dev/gpt and /dev/gptid dirs.

**Comment by lundman** [comment]
I don't have much of an opinion myself as I don't use ZVOL daily.  So I am ok with the changes you propose, especially since I did have to write the code :)  

subclassing IOBlockStorageDriver might be tempting, but also need to make sure it doesnt have issues with the 116_manual branch, since much of the IOKit code was changed.

There was talk about the idea of attaching IOKit partition to ZVOL device (just in IOKit, not on disk) so that HFS growing could work, but no research has been done with this at all.

**Comment by lundman** [comment]
Ok this is what we are thinking now.

* Abandon `snapdev` and `volmode` as they do not really fit with OSX
* Add `volautomount=on(default)/off` property to ZVOLs. (Not ZVOL snapshots)
* Add ZFS commands `zfs plug` and `zfs unplug` to be used by ZVOL snapshots

In detail, the `volautomount` should be possible to implement similar to how I controlled autodiskmount with dataset snapshots, ie:

https://github.com/openzfsonosx/zfs/blob/ac4418f14f944ab64f03661b165d983b55eb9a2e/module/zfs/ZFSProxyMediaScheme.cpp#L193

But set it to false if `volautomount=off` is set.

In addition, make
```
zpool import -o volautomount=off ...
zfs plug -o volautomount=off ...
zfs recv -o volautomount=off ...
```
work as expected, and add logic so that
```
zpool import -N
```
implies `volautomount=off`

As for zfs plug and unplug, the idea being to play with a ZVOL snapshot
```
zfs plug POOL/volume@snapshot
```
should create the /dev/diskX entry needed, and let DA mount it. Even though primarily, plug and unplug act on ZVOL snapshot, we could allow them to work on ZVOL themselves as well.

The default being then that ZVOLs get /dev/diskX always, but can be stopped from being mounted using ZVOL property, or import options.
ZVOL snapshots do not get /dev/diskX entry, but can add one manually using `zfs plug` command.

Feel free to work on it if you can, or I can once I get a bit further with 116. (Which can now automatically create a /dev/diskX entry for dataset snapshots with demand and automount - possibly making zfs plug command easier to implement.)

Questions, comments welcome :)

**Comment by ilovezfs** [comment]
I'm wondering if we should take this to the OpenZFS list since there's now snapdev on only ZoL, volmode only on FreeBSD, and possibly volautomount and zfs plug only on OS X.

**Comment by evansus** [comment]
@lundman sounds good to me. Any reason not to use the words "attach" and "detach" a la hdiutil? plug/unplug is OK too, just curious. @ilovezfs agreed

**Comment by ilovezfs** [comment]
Yes, attach/detach is nice if you don't mind that "zpool attach" and "zfs attach" would have very different meaning, but that could be treated as an RTFM issue even if it violates the principle of least surprise. Yet another pair would be connect/disconnect but that has network overtones.

**Comment by evansus** [comment]
https://github.com/openzfsonosx/zfs/commit/6d895f1ac847034fa768f2d9c5456badc96a2f98

**Pull request closed without merging**
