### PR TITLE
8423 Implement large_dnode pool feature

### PR DESCRIPTION
**Pull request by lundman**
8199 multi-threaded dmu_object_alloc()
7432 Large dnode pool feature

Reviewed by: Jerry Jelinek <jerry.jelinek@joyent.com>
Reviewed by: Jason King <jason.king@joyent.com>
Approved by: Dan McDonald <danmcd@joyent.com>

### CODE REVIEW

**Comment by lundman** [comment]
```
panic(cpu 1 caller 0xffffff8003e1283c): Kernel trap at 0xffffff7f87534c2d, type 14=page fault, registers:

0xffffff90b13e34e0 : 0xffffff8003c21ca0 mach_kernel : trap_from_kernel + 0x26
0xffffff90b13e3500 : 0xffffff7f87534c2d net.lundman.zfs : _sa_handle_object + 0xd
0xffffff90b13e3600 : 0xffffff7f874a2021 net.lundman.zfs : _dmu_tx_hold_sa + 0xc1
0xffffff90b13e3650 : 0xffffff7f876170f7 net.lundman.zfs : _zfs_vnop_pageoutv2 + 0x497

frame #1: 0xffffff7f874a2021 zfs`dmu_tx_hold_sa(tx=0xffffff90a384bc80, hdl=0x0000000000000000, may_grow=0) at dmu_tx.c:1319
   1316
   1317		ASSERT(hdl != NULL);
   1318
-> 1319		object = sa_handle_object(hdl);

(lldb) p hdl
(sa_handle_t *) $2 = 0x0000000000000000
```

**Comment by JMoVS** [comment]
I guess this means "not good" :D

**Comment by lundman** [comment]
Technically unrelated, its a pageoutv2 bug that occasionally shows up - looking at fixing it though

**Comment by lundman** [comment]
It's a problem with pageoutv2 - which has been for a while. I have attempted a real fix for it.

```
Results Summary
FAIL     237
KILLED     2
PASS     644

Running Time:   03:48:40
Percent passed: 72.9%
```

**Comment by lundman** [comment]
Seems to have got it
```
FAIL     236
KILLED     1
PASS     655

Running Time:   03:36:24
Percent passed: 73.4%
```

**Pull request merged**
