### PR TITLE
Issue116 lite

### PR DESCRIPTION
**Pull request by lundman**
This is code done mostly by @evansus and some minor tweaks by myself.

The complete Issue116 is undesirable due to the large changes in core-ZFS behaviour. This PR does minimalistic changes to `getmntany.c` and `zmount.c` by adding a new ioctl to request a new virtual `/dev/disk` to be created for the mount.

The default behaviour of mounts is controlled by the ZFS dataset property `com.apple.devdisk`.  The default value of this property is `poolonly`. Which means the "root" dataset of a pool will be `on` and all lower datsets will be `off`.  Each dataset can then set it to `on` individually, or if so desired, set the root dataset to `on` for lower inheritance.

The logic then follows:

`libzfs_mount.c` will issue a mount request by calling `zmount.c`.  Here we will lookup the `devdisk` property, and if it is either `on` or `poolonly && ispool` we will issue ioctl `ZFS_IOC_PROXY_DATASET`.

The kernel will create a new `/dev/disk` entry for the mount, and return the path in `zc.zc_value`. `zmount.c` will then issue the mount with `/dev/disk` path instead.

ZFS is called again in `zfs_vfs_mount()` where we translate the `/dev/disk` name to dataset name and mount procedure continues unchanged. At the end of mount, we set the `mountfromname` to the `/dev/disk` name.

When doing `is_mounted()` tests, as well as, **unmount** and **export** commands, the `getmntany()` call will see `/dev/disk` entries, and attempt to expand into ZFS dataset names. If it can, it will replace `/dev/disk` with the dataset name 'as normal'. The `libzfs` internal sources then remain unchanged. 

In ZFS `zfs_vfs_unmount()` we will release the `/dev/disk` node if one was used.

**Known Issues**

* Changing `devdisk` property while mounted will not automatically remount the dataset.

* It can break when looking for the pool proxy:
```
# zpool import BOOM
proxy dataset returns -1 ''
```

* It has had one panic, but unable to repeat.

Besides regular testing for bugs and problems, we should also check the list of problems in the Issue #116 ticket and see which items it corrects, and which it could correct with additional enhancements.

### CODE REVIEW

**Comment by ilovezfs** [comment]
>It has had one panic, but unable to repeat.

It happened again.

**Comment by lundman** [comment]
**Bug 1**

Ok so **import**, **export**, then **import** will trigger this, so it is a bit of a road block. Nothing is left in ioreg.

**Comment by lundman** [comment]
**Bug 2**

```
 "A kext releasing a(n) OSNumber has corrupted the registry."@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3789.60.24/libkern/c++/OSObject.cpp:200
Backtrace (CPU 1), Frame : Return Address
0xffffff8029a739e0 : 0xffffff80232ea53c mach_kernel : _panic + 0xec
0xffffff8029a73a60 : 0xffffff802383621e mach_kernel : __ZNK8OSObject13taggedReleaseEPKvi + 0x9e
0xffffff8029a73a80 : 0xffffff7fa65bb17d net.lundman.zfs : __ZN16ZFSDatasetScheme13removeDatasetEPKcb + 0x25d
0xffffff8029a73ad0 : 0xffffff7fa6576a1b net.lundman.zfs : _zfs_vfs_unmount + 0x62b
```

Now the fix that makes the partitions be recognised uses `provider->setProperty()` which surely is not legal? Or is the panic unrelated and more connected to making partition holes, later filled by a different mount.

**Comment by lundman** [comment]
**Bug 2**

This seems to be due to
```
ZFSDatasetScheme zfs_osx_proxy_scheme_by_osname couldn't get iterator
ZFSDatasetScheme zfs_osx_proxy_create can't get pool proxy
```

**Comment by lundman** [comment]
**Bug 3**

```
panic(cpu 1 caller 0xffffff802a796bc2): "A kext releasing a(n) OSNumber has corrupted the
registry."@/Library/Caches/com.apple.xbs/Sources/xnu_debug/xnu-3789.60.24/libkern/c++/
OSObject.cpp:200
```

which the source comment says:
```
    // This panic means that we have just attempted to release an object
    // whose retain count has gone to less than the number of collections
    // it is a member off.  Take a panic immediately.
    // In fact the panic MAY not be a registry corruption but it is
    // ALWAYS the wrong thing to do.  I call it a registry corruption 'cause
    // the registry is the biggest single use of a network of collections.
```

triggered by
```
frame #5: 0xffffff7fad5bb0ad zfs`ZFSDatasetScheme::removeDataset(this=<unavailable>, osname="testpool.454/testfs1.454/testfs2.454/testfs3.454/testclone454.3", force=<unavailable>) at ZFSDatasetScheme.cpp:1003 [opt]
   1000		/* Only return non-zero partition ids */
   1001		if (part_id != 0) {
   1002			dprintf("terminated partition %u", part_id);
-> 1003			returnPartitionID(part_id);
   1004		}
   1005
   1006		return (true);
```

**Comment by lundman** [comment]
Adding **noinline** to `returnPartitionID` we actually die in the tail:

```
	unlockForArbitration();
	/* Either was retained by setObject, or unused */
	OSSafeReleaseNULL(id_num);
```

`part_id == 5` and `_max_id == 3` which implies the `while` loop removed **4**, and exited loop on **3**.

**Comment by lundman** [comment]
The fix is a bit hacky in ecb2b6052a2b35af155a78746836154a050be256 so we need to try to correctly fix it.

**Comment by lundman** [comment]
Booting is currently broken.

**Comment by lundman** [comment]
Ok, squashed and ready for testing.  If people have time, see if it runs ok for you. @rottegift @brendonhumphrey @ilovezfs @evansus 

By default, you should when creating/importing pool, get the root dataset mounted as "/dev/disk*" and show in `diskutil list` under a virtual disk, with name. The other filesystems will not. If you set `com.apple.devdisk = on` on root dataset, then all datasets will get /dev/disk. Confirm mount/unmount, and export works as expected.

**Comment by ilovezfs** [comment]
Not sure `com.apple.devdisk` is the best name here.

**Comment by lundman** [comment]
Now is indeed the time to pick a different name, if you can think of one. I'm also not convinced we should have gone with "com.apple." any longer :)

**Comment by ilovezfs** [comment]
`net.lundman.116` maybe

**Comment by lundman** [comment]
There is a bug with unmounting **sometimes** - where it will say
```
17:41:49.53 Running process: '/usr/sbin/diskutil' 'unmount' '/testpool.464'
17:41:49.57 disk4s1 was already unmounted
```

No amount of harsh language to `diskutil` will make it succeed. It is easy to work around with a `/sbin/umount /testpool.464` - but it does need a fix. Something to do with the new iokit virtual disks.

**Comment by lundman** [comment]
Apparently ZVOL boot is failing.

**Comment by JMoVS** [comment]
isn't this pull request no longer relevant?

**Comment by lundman** [comment]
it was joined into master some time back

**Comment by lundman** [comment]
merged a while back.

**Pull request closed without merging**
