### PR TITLE
zfs.fs Probe order decrease

### PR DESCRIPTION
**Pull request by cbreak-black**
To avoid issues with preventing certain devices from being mounted by
other file systems, decrease the probe priority of zfs. See Issue #571.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Note this could potentially be dangerous if the device had a preexisting file system before the pool was created and the driver for the other file system attempts to mount it first.

**Comment by cbreak-black** [comment]
In my case, the filesystem is a "msdos" whole disk filesystem without zfs involved, so ZFS should not prevent it from being mounted normally. Without this change, zfs does prevent it from mounting normally.

**Comment by ilovezfs** [comment]
That sounds like a bug that we don't give it and return probe failure.

**Comment by cbreak-black** [comment]
I updated my "fix" to be based on the latest master, at time of writing this.

**Pull request merged**
