### PR TITLE
ZoL assembler port

### PR DESCRIPTION
**Pull request by lundman**
This PR brings in the ZoL assembler work, which includes; sse, sse2, sse3, ssse3, sse4_1, sse4_2, avx, avx2, bmi1, bmi2, aes, aesni, pclmulqdq, avx512 + (f, cd, er, pf, bw, dq, vl, ifma, vbmi), scalar, superscalar, superscalar4.

Unfortunately, the best my hardware can go, is SSSE3 + AESNI. Others with newer CPUs might need to check that SSE4, BMI, and AVX512* work.

The ZoL framework also bring in the ability to select implementation, in the form of new kstats;

```
kstat.zfs.darwin.tunable.zfs_vdev_raidz_impl: [fastest] original scalar sse2 ssse3
kstat.zfs.darwin.tunable.icp_gcm_impl: cycle [fastest] generic pclmulqdq
kstat.zfs.darwin.tunable.icp_aes_impl: cycle [fastest] generic x86_64 aesni
kstat.zfs.darwin.tunable.zfs_fletcher_4_impl: [fastest] scalar superscalar superscalar4 sse2 ssse3
```
To change the preferred implementation, use something like:
`sysctl kstat.zfs.darwin.tunable.zfs_fletcher_4_impl=superscaler4`.

The default is `fastest` which generally is the last ability probed, or in the case of `zfs_fletcher`, based on the quick benchmarking it does on kext load time. Enable printfs if you wish to see the result. We currently do not support `raw kstat` type, which is why there are printfs.

We already had some assembler implementation in the OsX repository, but these files have been renamed over to fit with upstream's layout and names.

This PR depends on SPL `zol_raidz` branch, for the `cpuid_features()` wrapper and port of `simd_x86.h` header file.

### CODE REVIEW

**Comment by yurikoles** [comment]
I have Core i5 9600K and I want to test out new instructions, which your CPU lacks.

Could you give me some instructions on this?

**Comment by lundman** [comment]
Have you compiled O3X on your own in the past, or willing to do so? Otherwise, I can create you a new PKG to test.

**Comment by yurikoles** [comment]
I have experience building O3X.

**Comment by lundman** [comment]
Checkout out branch `zol_async` on both SPL and ZFS, compile and test.

**Comment by yurikoles** [comment]
Did you meant `zol_raidz`? Do I need to create RAIDZ to test it?

**Comment by lundman** [comment]
Oops, you are right, yes this PR. And no, it just started with me porting over the raidz assembler work, but then figured I might as well do encryption, compression and fletcher at the same time.

fletcher and raidz are the only ones with AVX512 though - you don't have to use a real pool, you can create 3 files on disk and create a raidz pool on those files.

**Comment by hoondi** [comment]
So the newly added code to use instruction sets…

Is it utilised for anything else other than compression/encryption? Am curious if we’re to expect see any I/O performance in other areas.

**Comment by lundman** [comment]
Presumably it will speed up encryption, pools with checksum=fletcher, pools with raidz.

Not compression, that was QAT code - which appears to not have drivers for OsX.

**Comment by yurikoles** [comment]
I had frequent system resets on this branch on Catalina. Especially on volume manipulation, but not limited to it, even `zfs list -r <pool>` may cause reset.

I can provide logs If you need them, just give me a hint where to get them.

**Comment by yurikoles** [comment]
@lundman could you please rebase this PR?

**Comment by lundman** [comment]
This PR is now in master branch.

**Comment by lundman** [comment]
We commented out the AVX512 code in master, as it has problems with new CPUs.

**Comment by yurikoles** [comment]
> This PR is now in master branch.

Then please consider closing it.

**Pull request closed without merging**
