### PR TITLE
Multi-modifier protection (MMP)

### PR DESCRIPTION
**Pull request by lundman**
Add multihost=on|off pool property to control MMP.  When enabled
a new thread writes uberblocks to the last slot in each label, at a
set frequency, to indicate to other hosts the pool is actively imported.
These uberblocks are the last synced uberblock with an updated
timestamp.  Property defaults to off.

During tryimport, find the "best" uberblock (newest txg and timestamp)
repeatedly, checking for change in the found uberblock.  Include the
results of the activity test in the config returned by tryimport.
These results are reported to user in "zpool import".

Allow the user to control the period between MMP writes, and the
duration of the activity test on import, via a new module parameter
zfs_multihost_interval.  The period is specified in milliseconds.  The
activity test duration is calculated from this value, and from the
mmp_delay in the "best" uberblock found initially.

Add a kstat interface to export statistics about Multiple Modifier
Protection (MMP) updates. Include the last synced txg number, the
timestamp, the delay since the last MMP update, the VDEV GUID, the VDEV
label that received the last MMP update, and the VDEV path.  Abbreviated
output below.

$ cat /proc/spl/kstat/zfs/mypool/multihost
31 0 0x01 10 880 105092382393521 105144180101111
txg   timestamp  mmp_delay   vdev_guid   vdev_label vdev_path
20468    261337  250274925   68396651780       3    /dev/sda
20468    261339  252023374   6267402363293     1    /dev/sdc
20468    261340  252000858   6698080955233     1    /dev/sdx
20468    261341  251980635   783892869810      2    /dev/sdy
20468    261342  253385953   8923255792467     3    /dev/sdd
20468    261344  253336622   042125143176      0    /dev/sdab
20468    261345  253310522   1200778101278     2    /dev/sde
20468    261346  253286429   0950576198362     2    /dev/sdt
20468    261347  253261545   96209817917       3    /dev/sds
20468    261349  253238188   8555725937673     3    /dev/sdb

Add a new tunable zfs_multihost_history to specify the number of MMP
updates to store history for. By default it is set to zero meaning that
no MMP statistics are stored.

When using ztest to generate activity, for automated tests of the MMP
function, some test functions interfere with the test.  For example, the
pool is exported to run zdb and then imported again.  Add a new ztest
function, "-M", to alter ztest behavior to prevent this.

Add new tests to verify the new functionality.  Tests provided by
Giuseppe Di Natale.

Reviewed by: Matthew Ahrens <mahrens@delphix.com>
Reviewed-by: Giuseppe Di Natale <dinatale2@llnl.gov>
Reviewed-by: Ned Bass <bass6@llnl.gov>
Reviewed-by: Andreas Dilger <andreas.dilger@intel.com>
Reviewed-by: Brian Behlendorf <behlendorf1@llnl.gov>
Signed-off-by: Olaf Faaland <faaland1@llnl.gov>

### CODE REVIEW

**Comment by behlendorf** [comment]
Here are a few minor fixes I didn't see listed.

zfsonlinux/zfs@b6e5c40382a5 Use correct macro for hz in mmp.c
zfsonlinux/zfs@802ae562ed81 Fix coverity defects: CID 165755
zfsonlinux/zfs@bc5f51c5de21 module param callbacks check for initialized spa

There are two additional mmp PRs out for review which make further improvements but aren't quite ready.

https://github.com/zfsonlinux/zfs/pull/7953 rotate over leaves for mmp writes
https://github.com/zfsonlinux/zfs/pull/7842 MMP should specify wait time in uberblock

**Comment by lundman** [comment]
Thank you @behlendorf as it happens the first one I fixed by hand as I couldn't get it to compile. I skipped over the "module param" one as we do not have module params, but thinking maybe I'll pull it in so that the init code layout is the same. Probably a good idea.

**Comment by allanjude** [comment]
I ended up needing https://github.com/zfsonlinux/zfs/commit/0091d66f4ebfeb83f70212ab92a4d5a8e4a9c4dc as well, to prevent panics in vdev_label_write()

**Comment by JMoVS** [comment]
this one was already merged, right?

**Pull request closed without merging**
